# Generated by Django 4.2.6 on 2024-02-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='Admin',
            field=models.CharField(default='', max_length=20),
        ),
    ]
